"""Add verification fields to stores

Revision ID: 235c240b447a
Revises: aa7bd2a621f6
Create Date: 2026-01-27 15:29:35.734573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235c240b447a'
down_revision: Union[str, Sequence[str], None] = 'aa7bd2a621f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('commercial_registration_url', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('id_card_url', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('store_front_photo_url', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('stores', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'verified_at')
    op.drop_column('stores', 'verification_notes')
    op.drop_column('stores', 'gps_longitude')
    op.drop_column('stores', 'gps_latitude')
    op.drop_column('stores', 'store_front_photo_url')
    op.drop_column('stores', 'id_card_url')
    op.drop_column('stores', 'commercial_registration_url')
    op.drop_column('stores', 'is_verified')
    # ### end Alembic commands ###
