"""Add missing RBAC and support tables

Revision ID: 6a258446c576
Revises: e3a9b1d2c4f7
Create Date: 2026-01-31 01:48:31.064977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a258446c576'
down_revision: Union[str, Sequence[str], None] = 'e3a9b1d2c4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_admin_roles_id'), 'admin_roles', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'BILLING', 'PRODUCT', 'SHIPPING', 'ACCOUNT', 'OTHER', name='ticketcategory'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=False)
    op.drop_constraint(op.f('audit_logs_admin_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('couriers_user_id_fkey'), 'couriers', type_='foreignkey')
    op.create_foreign_key(None, 'couriers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_history_changed_by_id_fkey'), 'order_history', type_='foreignkey')
    op.drop_constraint(op.f('order_history_order_id_fkey'), 'order_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_history', 'users', ['changed_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'order_payments', type_='foreignkey')
    op.create_foreign_key(None, 'order_payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orders_courier_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['courier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('store_users_user_id_fkey'), 'store_users', type_='foreignkey')
    op.create_foreign_key(None, 'store_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subscription_payments_invoice_id_fkey'), 'subscription_payments', type_='foreignkey')
    op.drop_constraint(op.f('subscription_payments_subscription_id_fkey'), 'subscription_payments', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscription_payments', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subscription_webhooks_payment_id_fkey'), 'subscription_webhooks', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_webhooks', 'subscription_payments', ['payment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_webhooks', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_webhooks_payment_id_fkey'), 'subscription_webhooks', 'subscription_payments', ['payment_id'], ['id'])
    op.drop_constraint(None, 'subscription_payments', type_='foreignkey')
    op.drop_constraint(None, 'subscription_payments', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_payments_subscription_id_fkey'), 'subscription_payments', 'subscriptions', ['subscription_id'], ['id'])
    op.create_foreign_key(op.f('subscription_payments_invoice_id_fkey'), 'subscription_payments', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint(None, 'store_users', type_='foreignkey')
    op.create_foreign_key(op.f('store_users_user_id_fkey'), 'store_users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('orders_courier_id_fkey'), 'orders', 'users', ['courier_id'], ['id'])
    op.drop_constraint(None, 'order_payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'order_payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_history', type_='foreignkey')
    op.drop_constraint(None, 'order_history', type_='foreignkey')
    op.create_foreign_key(op.f('order_history_order_id_fkey'), 'order_history', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_history_changed_by_id_fkey'), 'order_history', 'users', ['changed_by_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'couriers', type_='foreignkey')
    op.create_foreign_key(op.f('couriers_user_id_fkey'), 'couriers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_admin_id_fkey'), 'audit_logs', 'users', ['admin_id'], ['id'])
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_admin_roles_id'), table_name='admin_roles')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
