"""Add store verification fields

Revision ID: 7ab1481deaec
Revises: 235c240b447a
Create Date: 2026-01-28 05:27:52.729677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab1481deaec'
down_revision: Union[str, Sequence[str], None] = '235c240b447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    storeverificationstatus = sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='storeverificationstatus')
    storeverificationstatus.create(op.get_bind())

    op.add_column(
        'stores',
        sa.Column(
            'verification_status',
            storeverificationstatus,
            nullable=True,
        ),
    )
    op.add_column('stores', sa.Column('verified_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stores_verification_status'), 'stores', ['verification_status'], unique=False)
    op.create_foreign_key(
        'fk_stores_verified_by_id_users',
        'stores',
        'users',
        ['verified_by_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stores_verified_by_id_users', 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_verification_status'), table_name='stores')
    op.drop_column('stores', 'verified_by_id')
    op.drop_column('stores', 'verification_status')
    sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='storeverificationstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
