"""add city and district to store

Revision ID: 91e1ad3e92d2
Revises: 467a3999d72d
Create Date: 2026-01-26 05:59:04.153178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e1ad3e92d2'
down_revision: Union[str, Sequence[str], None] = '467a3999d72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('city', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('district', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'district')
    op.drop_column('stores', 'city')
    # ### end Alembic commands ###
