"""Sync payments and order_payments schema

Revision ID: 9b776672b4df
Revises: 69f2a304c2ae
Create Date: 2026-01-26 12:18:32.438351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b776672b4df'
down_revision: Union[str, Sequence[str], None] = '69f2a304c2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename table instead of drop/create to preserve data and enums
    op.rename_table('payments', 'order_payments')
    
    # Rename indexes
    op.execute('ALTER INDEX ix_payments_id RENAME TO ix_order_payments_id')
    op.execute('ALTER INDEX ix_payments_store_id RENAME TO ix_order_payments_store_id')
    # Use standard index rename if possible, but execute is safer for PG
    op.create_index(op.f('ix_order_payments_order_id'), 'order_payments', ['order_id'], unique=False)

    op.alter_column('subscription_payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_subscription_payments_invoice_id'), 'subscription_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    
    # These columns were added in 69f2a304c2ae, but maybe we want to keep them or drop them?
    # The current code doesn't have them in Subscription model anymore.
    # op.drop_column('subscriptions', 'payment_method')
    # op.drop_column('subscriptions', 'last_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_invoice_id'), table_name='subscription_payments')
    op.alter_column('subscription_payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('method', postgresql.ENUM('CASH_ON_DELIVERY', 'BANK_TRANSFER', 'ONLINE_PAYMENT', 'WALLET', name='paymentmethod'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'REJECTED', name='paymentstatus'), autoincrement=False, nullable=True),
    sa.Column('transaction_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proof_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('payments_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('payments_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_payments_store_id'), 'payments', ['store_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_index(op.f('ix_order_payments_store_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_order_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_id'), table_name='order_payments')
    op.drop_table('order_payments')
    # ### end Alembic commands ###
