"""Fix store subscription relationship

Revision ID: a069d3e0ccfb
Revises: c6edda8e4e6f
Create Date: 2026-01-26 10:21:32.598410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a069d3e0ccfb'
down_revision: Union[str, Sequence[str], None] = 'c6edda8e4e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stores_subscription_id_fkey'), 'stores', type_='foreignkey')
    op.drop_column('stores', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('stores_subscription_id_fkey'), 'stores', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
