"""Add store payment methods

Revision ID: b0d86db06079
Revises: 9b776672b4df
Create Date: 2026-01-27 11:18:58.129072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b0d86db06079'
down_revision: Union[str, Sequence[str], None] = '9b776672b4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type manually if it doesn't exist
    payment_method_enum = postgresql.ENUM('CASH_ON_DELIVERY', 'BANK_TRANSFER', 'ONLINE_PAYMENT', 'WALLET', name='paymentmethod')
    payment_method_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('store_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('method_type', postgresql.ENUM('CASH_ON_DELIVERY', 'BANK_TRANSFER', 'ONLINE_PAYMENT', 'WALLET', name='paymentmethod', create_type=False), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_payment_methods_id'), 'store_payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_store_payment_methods_store_id'), 'store_payment_methods', ['store_id'], unique=False)
    op.add_column('order_payments', sa.Column('store_payment_method_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('payments_order_id_key'), 'order_payments', type_='unique')
    op.create_foreign_key(None, 'order_payments', 'store_payment_methods', ['store_payment_method_id'], ['id'])
    op.drop_column('subscriptions', 'payment_method')
    op.drop_column('subscriptions', 'last_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_payments', type_='foreignkey')
    op.create_unique_constraint(op.f('payments_order_id_key'), 'order_payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('order_payments', 'store_payment_method_id')
    op.drop_index(op.f('ix_store_payment_methods_store_id'), table_name='store_payment_methods')
    op.drop_index(op.f('ix_store_payment_methods_id'), table_name='store_payment_methods')
    op.drop_table('store_payment_methods')
    # ### end Alembic commands ###
